[package]
name = "black_hole_modeler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assimp-sys = "0.3.1"
black_hole = { git = "https://github.com/swolelmo/blackhole.git"}
glam = "0.23.0"
