[package]
name = "black_hole_modeler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
russimp = { version = "2.0.6", features = ["prebuilt"] }
